/********************************************************************
* eventDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error eventDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableeventDict();
extern void G__cpp_setup_inheritanceeventDict();
extern void G__cpp_setup_typetableeventDict();
extern void G__cpp_setup_memvareventDict();
extern void G__cpp_setup_globaleventDict();
extern void G__cpp_setup_memfunceventDict();
extern void G__cpp_setup_funceventDict();
extern void G__set_cpp_environmenteventDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "RawAraTestBedStationHeader.h"
#include "RawAraTestBedStationEvent.h"
#include "RawAraStationEvent.h"
#include "FullAraTestBedHkEvent.h"
#include "UsefulAraStationEvent.h"
#include "AraEventCalibrator.h"
#include "AraTestBedTriggerMonitor.h"
#include "AraTestBedHkData.h"
#include "AraRawTestBedRFChannel.h"
#include "AraAntennaInfo.h"
#include "AraGeomTool.h"
#include "UsefulAraStationEvent.h"
#include "UsefulAraTestBedStationEvent.h"
#include "araTestbedStructures.h"
#include "AraOneEventHkData.h"
#include "AraOneSensorHkData.h"
#include "araOneStructures.h"
#include "araTestBedDefines.h"
#include "RawAraOneSimpleStationEvent.h"
#include "RawAraOneStationBlock.h"
#include "RawAraOneGenericHeader.h"
#include "RawAraOneStationEvent.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__eventDictLN_TClass;
extern G__linked_taginfo G__eventDictLN_TBuffer;
extern G__linked_taginfo G__eventDictLN_TMemberInspector;
extern G__linked_taginfo G__eventDictLN_TObject;
extern G__linked_taginfo G__eventDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__eventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__eventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__eventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__eventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__eventDictLN_AraTestBedTriggerMonitorStruct_t;
extern G__linked_taginfo G__eventDictLN_AraTestBedAraTestBedRFChannelFull_t;
extern G__linked_taginfo G__eventDictLN_AraTestBedEventHeader_t;
extern G__linked_taginfo G__eventDictLN_AraTestBedHkDataStruct_t;
extern G__linked_taginfo G__eventDictLN_AraTestBedEventBody_t;
extern G__linked_taginfo G__eventDictLN_AraTestBedHkBody_t;
extern G__linked_taginfo G__eventDictLN_RawAraTestBedStationHeader;
extern G__linked_taginfo G__eventDictLN_RawAraStationEvent;
extern G__linked_taginfo G__eventDictLN_AraRawTestBedRFChannel;
extern G__linked_taginfo G__eventDictLN_AraTestBedTriggerMonitor;
extern G__linked_taginfo G__eventDictLN_AraTestBedHkData;
extern G__linked_taginfo G__eventDictLN_RawAraTestBedStationEvent;
extern G__linked_taginfo G__eventDictLN_FullAraTestBedHkEvent;
extern G__linked_taginfo G__eventDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__eventDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__eventDictLN_TGraph;
extern G__linked_taginfo G__eventDictLN_TH1D;
extern G__linked_taginfo G__eventDictLN_AraCalType;
extern G__linked_taginfo G__eventDictLN_AraCalTypecLcLEAraCalType;
extern G__linked_taginfo G__eventDictLN_UsefulAraTestBedStationEvent;
extern G__linked_taginfo G__eventDictLN_AraEventCalibrator;
extern G__linked_taginfo G__eventDictLN_UsefulAraStationEvent;
extern G__linked_taginfo G__eventDictLN_AraAntType;
extern G__linked_taginfo G__eventDictLN_AraAntTypecLcLEAraAntType;
extern G__linked_taginfo G__eventDictLN_AraAntPol;
extern G__linked_taginfo G__eventDictLN_AraAntPolcLcLEAraAntPol;
extern G__linked_taginfo G__eventDictLN_AraDaqChanType;
extern G__linked_taginfo G__eventDictLN_AraDaqChanTypecLcLEAraDaqChanType;
extern G__linked_taginfo G__eventDictLN_AraLabChip;
extern G__linked_taginfo G__eventDictLN_AraLabChipcLcLEAraLabChip;
extern G__linked_taginfo G__eventDictLN_AraAntDir;
extern G__linked_taginfo G__eventDictLN_AraAntDircLcLEAraAntDir;
extern G__linked_taginfo G__eventDictLN_AraSurfaceOrientation;
extern G__linked_taginfo G__eventDictLN_AraSurfaceOrientationcLcLEAraSurfaceOrientation;
extern G__linked_taginfo G__eventDictLN_AraAntennaInfo;
extern G__linked_taginfo G__eventDictLN_AraGeomTool;
extern G__linked_taginfo G__eventDictLN_AraGenericHeader_t;
extern G__linked_taginfo G__eventDictLN_AraEventHk_t;
extern G__linked_taginfo G__eventDictLN_AraSensorHk_t;
extern G__linked_taginfo G__eventDictLN_AraSimpleStationEvent_t;
extern G__linked_taginfo G__eventDictLN_AraStationEventHeader_t;
extern G__linked_taginfo G__eventDictLN_AraStationEventBlockHeader_t;
extern G__linked_taginfo G__eventDictLN_AraStationEventBlockChannel_t;
extern G__linked_taginfo G__eventDictLN_RawAraOneGenericHeader;
extern G__linked_taginfo G__eventDictLN_AraOneEventHkData;
extern G__linked_taginfo G__eventDictLN_AraOneSensorHkData;
extern G__linked_taginfo G__eventDictLN_RawAraOneSimpleStationEvent;
extern G__linked_taginfo G__eventDictLN_RawAraOneStationBlock;
extern G__linked_taginfo G__eventDictLN_vectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgR;
extern G__linked_taginfo G__eventDictLN_reverse_iteratorlEvectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__eventDictLN_RawAraOneStationEvent;
extern G__linked_taginfo G__eventDictLN_vectorlERawAraOneStationBlockcOallocatorlERawAraOneStationBlockgRsPgR;
extern G__linked_taginfo G__eventDictLN_reverse_iteratorlEvectorlERawAraOneStationBlockcOallocatorlERawAraOneStationBlockgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
