MESSAGE(STATUS "Looking for libRootFftwWrapper...")

# We need FFTW.
find_package(FFTW)
# And we need ROOT, with MathMore and Gui.
find_package(ROOT COMPONENTS MathMore Gui)

SET(FFTTOOLS_H_SEARCH_PATH
  "$ENV{ANITA_UTIL_INSTALL_DIR}/include"
  "$ENV{ARA_UTIL_INSTALL_DIR}/include"
  /usr/include
  /usr/local/include
)
SET(LIBROOTFFTWWRAPPER_SEARCH_PATH
  "$ENV{ANITA_UTIL_INSTALL_DIR}/lib"
  "$ENV{ARA_UTIL_INSTALL_DIR}/lib"
)

FIND_PATH(LIBROOTFFTWWRAPPER_INCLUDE_DIR FFTtools.h PATHS ${FFTTOOLS_H_SEARCH_PATH})
IF (${LIBROOTFFTWWRAPPER_INCLUDE_DIR} MATCHES "LIBROOTFFTWWRAPPER_INCLUDE_DIR-NOTFOUND")
  MESSAGE( FATAL_ERROR "libRootFftwWrapper not installed in \"${FFTTOOLS_H_SEARCH_PATH}. Please set ANITA_UTIL_INSTALL_DIR or ARA_UTIL_INSTALL_DIR or add the path in the macro FindlibRootFftwWrapper.cmake.")
ENDIF (${LIBROOTFFTWWRAPPER_INCLUDE_DIR} MATCHES "LIBROOTFFTWWRAPPER_INCLUDE_DIR-NOTFOUND")

FIND_LIBRARY(LIBROOTFFTWWRAPPER_LIBRARY RootFftwWrapper libRootFftwWrapper PATHS ${LIBROOTFFTWWRAPPER_SEARCH_PATH})

# Specify THIS library first, THEN libraries it depends upon
# so that the linker searches them afterwards.
SET(LIBROOTFFTWWRAPPER_LIBRARIES ${LIBROOTFFTWWRAPPER_LIBRARY} ${ROOT_LIBRARIES} ${ROOT_MATHMORE_LIBRARY} ${FFTW_LIBRARIES})

SET(LIBROOTFFTWWRAPPER_INCLUDE_DIRS ${LIBROOTFFTWWRAPPER_INCLUDE_DIR} ${FFTW_INCLUDES})
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(LibRootFftwWrapper DEFAULT_MSG
  LIBROOTFFTWWRAPPER_LIBRARY LIBROOTFFTWWRAPPER_INCLUDE_DIR)
mark_as_advanced(LIBROOT_FFTWWRAPPER_INCLUDE_DIR LIBROOT_FFTWWRAPPER_LIBRARY)
