name: test_araroot
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

      - uses: actions/checkout@v2


      - name: Install dependencies
        run: |
          
          sudo apt-get install dpkg-dev cmake g++ gcc binutils libx11-dev \
           libxpm-dev libxft-dev libxext-dev python libssl-dev libfftw3-dev \
           libgsl-dev libboost-dev sqlite3 libsqlite3-dev


      - name: Install ROOT
        run: |
          
          wget -q https://root.cern/download/root_v6.22.06.Linux-ubuntu20-x86_64-gcc9.3.tar.gz
          tar -xzf root_v6.22.06.Linux-ubuntu20-x86_64-gcc9.3.tar.gz
          source root/bin/thisroot.sh
          root --version


      - name: Install libRootFftwWrapper
        run: |
          
          source root/bin/thisroot.sh

          # download
          wget -q https://github.com/nichol77/libRootFftwWrapper/archive/master.tar.gz -O libRootFftwWrapper.tar.gz
          mkdir libRootFftwWrapper
          tar -xzf libRootFftwWrapper.tar.gz -C libRootFftwWrapper --strip-components=1
          rm libRootFftwWrapper.tar.gz
          

          # build
          cd libRootFftwWrapper
          make -j2
          sudo make install

      - name: Build AraRoot
        run: |

          source root/bin/thisroot.sh
          export ARA_ROOT_DIR=$PWD
          mkdir the_build
          export ARA_UTIL_INSTALL_DIR=$PWD/the_build
          bash INSTALL.sh 1

      - name: Run AraRoot tests
        run: |

          source root/bin/thisroot.sh
          export ARA_ROOT_DIR=$PWD
          export ARA_UTIL_INSTALL_DIR=$PWD/the_build
          bash INSTALL.sh test
          
